apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-go-api
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-go-api
  template:
    metadata:
      labels:
        app: dummy-go-api
    spec:
      containers:
        - name: dummy-go-api
          image: registry.dev.analyticshq.com/kevtest2/dummy-go-api:v2
          ports:
            - containerPort: 9090
      imagePullSecrets:
        - name: regcred-harbor
