---
apiVersion: v1
kind: Service
metadata:
  name: dummy-go-api-svc
  namespace: app
spec:
  selector:
    app: dummy-go-api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
